name: MintaFresh Website Development

on:
  push:
    branches:
      - main

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    step: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx  
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mintafresh/website:latest   

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "pulling latest docker image"
            sudo docker pull mintafresh/website:latest

            echo "Navigating to minta-fresh directory..."
            cd /root/minta-fresh-website

            echo "Rebuilding and restarting services..."
            sudo docker compose up -d 

            echo "Deployment successful ✅"

            echo "Cleaning up..."
            sudo docker system prune -f    